### ISSUE TITLE
新的开始 | David's Blog

### ISSUE THREAD

**Issue by yuxianyu** [yuxianyu/yuxianyu.github.io#5]
https://yuxianyu.github.io/post/xin-de-kai-shi/ 

 余弦咸鱼 - 渣渣的博客

**Comment by huanblog** [comment]
Hi, Dalao. This is a comment.
Nice to see your blog again. By the way, I registered my first GitHub account. In brief, sdl, tql, wsl.

**Comment by yuxianyu** [comment]
> @huanblog
> Hi, Dalao. This is a comment.
> Nice to see your blog again. By the way, I registered my first GitHub account. In brief, sdl, tql, wsl.

Long time no see, Dalao!
Welcome to my new blog. We can have PYs together~
